---
- name: Audit | SUDO | Include chapter controls
  ansible.builtin.include_tasks:
    file: sudo.yml
  tags: [cis, audit, alt, sudo, chapter_sudo]

- name: Audit | Bootloader | Include chapter controls
  ansible.builtin.include_tasks:
    file: bootloader.yml
  tags: [cis, audit, alt, bootloader, chapter_bootloader]

- name: Audit | Banners | Include chapter controls
  ansible.builtin.include_tasks:
    file: banners.yml
  tags: [cis, audit, alt, banners, chapter_banners]

- name: Audit | PAM | Include chapter controls
  ansible.builtin.include_tasks:
    file: pam.yml
  tags: [cis, audit, alt, pam, chapter_pam]

- name: Audit | Cron&At | Include chapter controls
  ansible.builtin.include_tasks:
    file: cron_at.yml
  tags: [cis, audit, alt, cron_at, chapter_cron_at]

- name: Audit | SSHD | Include chapter controls
  ansible.builtin.include_tasks:
    file: sshd.yml
  tags: [cis, audit, alt, sshd, chapter_sshd]

- name: Audit | Local Users and Groups | Include chapter controls
  ansible.builtin.include_tasks:
    file: local_users_groups.yml
  tags: [cis, audit, alt, local_users_groups, chapter_local_users_groups]

- name: Audit | FilePermission | Include chapter controls
  ansible.builtin.include_tasks:
    file: file_permission.yml
  tags: [cis, audit, alt, file_permission, chapter_file_permission]

- name: Audit | Passwords | Include chapter controls
  ansible.builtin.include_tasks:
    file: passwords.yml
  tags: [cis, audit, alt, passwords, chapter_passwords]

- name: Audit | Root&System Accounts | Include chapter controls
  ansible.builtin.include_tasks:
    file: root_system_accounts.yml
  tags: [cis, audit, alt, root_system_accounts, chapter_root_system_accounts]

- name: Audit | Process Hardening | Include chapter controls
  ansible.builtin.include_tasks:
    file: process_hardening.yml
  tags: [cis, audit, alt, process_hardening, chapter_process_hardening]

- name: Audit | Filesystem | Include chapter controls
  ansible.builtin.include_tasks:
    file: filesystem.yml
  tags: [cis, audit, alt, filesystem, chapter_filesystem]

- name: Audit | Time Sync | Include chapter controls
  ansible.builtin.include_tasks:
    file: time_sync.yml
  tags: [cis, audit, alt, time_sync, chapter_time_sync]


- name: Audit | Logging | Include chapter controls
  ansible.builtin.include_tasks:
    file: logging.yml
  tags: [cis, audit, alt, logging, chapter_logging]

- name: Audit | SERVICES | Include chapter controls
  ansible.builtin.include_tasks:
    file: services.yml
  tags: [cis, audit, alt, services, chapter_services]

- name: Audit | Network Kernel Modules | Include chapter controls
  ansible.builtin.include_tasks:
    file: network_kernel_modules.yml
  tags: [cis, audit, alt, network_kernel_modules, chapter_network_kernel_modules]
